name: happenings
description: "Keep track of happenings."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.9.0
  cupertino_icons: ^1.0.6
  drift: ^2.16.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  path: ^1.9.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.4
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  drift_dev: ^2.16.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
